# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Weekly Team Sync
on:
  schedule:
    - cron: 20 07 * * 1

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "brooksseahorn, mattdavis0351"
          labels: "bug"
          title: "Weekly Team Sync"
          body: |
            ### Agenda

            - [ ] Start the recording
            - [ ] Check-ins

                    
            ### Discussion Points
            Add things to discuss below

          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
